keys:
  - &daniel 7062369036F842822CA109C2660DBDE129F4E1D9
  - &phantom age16hhp7r980a2ycadax9mmyy9z3yghyt24xslnt9m8cm9z2rpt833saw2myq
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - pgp:
      - *daniel
      age:
      - *phantom

