#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -gt 0 ]; then
  nix fmt "$@"
  exit 0
fi

mapfile -d '' files < <(
  fd \
    --hidden \
    --type f \
    --extension nix \
    --exclude .git \
    --exclude .direnv \
    --exclude result \
    --print0
)

if [ "${#files[@]}" -eq 0 ]; then
  exit 0
fi

nix fmt "${files[@]}"
